from django.urls import path

from . import views

app_name = "inventory"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.local_login, name="local_login"),
    path("logout/", views.local_logout, name="local_logout"),
    path("account/", views.account_page, name="account"),
    path("account/notifications/read/", views.notifications_mark_read, name="notifications_mark_read"),
    path("account/notifications/delete-all/", views.notifications_delete_all, name="notifications_delete_all"),
    path("account/edit/", views.account_edit, name="account_edit"),
    path("guest-login/", views.guest_login, name="guest_login"),
    path("onboarding/mark-seen/", views.mark_onboarding_seen, name="mark_onboarding_seen"),
    path("transaction/", views.process_transaction, name="process_transaction"),
    path("scan/", views.scan_item, name="scan_item"),
    path("return-by-code/", views.return_by_code, name="return_by_code"),
    path("announcements/", views.announcements_page, name="announcements"),
    path("announcements/post/", views.post_announcement, name="post_announcement"),
    path("announcements/<int:pk>/edit/", views.announcement_edit, name="announcement_edit"),
    path("announcements/<int:pk>/toggle/", views.announcement_toggle, name="announcement_toggle"),
    path("announcements/<int:pk>/pin/", views.announcement_pin, name="announcement_pin"),
    path("announcements/<int:pk>/delete/", views.announcement_delete, name="announcement_delete"),
    path("requests/", views.requests_page, name="requests"),
    path("requests/slip/<str:code>/", views.request_slip, name="request_slip"),
    path("requests/<int:pk>/receipt/", views.request_receipt, name="request_receipt"),
    path("requests/<int:pk>/void/", views.request_void, name="request_void"),
    path("transactions/<int:pk>/void/", views.transaction_void, name="transaction_void"),
    path("requests/<int:pk>/email-slip/", views.request_email_slip, name="request_email_slip"),
    path("requests/<int:pk>/approve/", views.request_approve, name="request_approve"),
    path("requests/<int:pk>/reject/", views.request_reject, name="request_reject"),
    path("requests/<int:pk>/hand-over/", views.request_hand_over, name="request_hand_over"),
    path("requests/lookup-code/", views.request_lookup_code, name="request_lookup_code"),
    path("requests/<int:pk>/edit/", views.request_edit, name="request_edit"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("maintenance/", views.maintenance_list, name="maintenance"),
    path("maintenance/<int:pk>/", views.maintenance_detail, name="maintenance_detail"),
    path("maintenance/start/", views.maintenance_start, name="maintenance_start"),
    path("maintenance/<int:pk>/complete/", views.maintenance_complete, name="maintenance_complete"),
    path("maintenance/<int:pk>/write-off/", views.maintenance_write_off, name="maintenance_write_off"),
    path("landing/", views.landing, name="landing"),
    path("staff/", views.staff_home, name="staff_home"),
    path("teacher/", views.teacher_home, name="teacher_home"),
    path("catalog/", views.catalog, name="catalog"),
    path("item-lookup/", views.item_lookup, name="item_lookup"),
    path("cart/add/", views.cart_add, name="cart_add"),
    path("cart/remove/", views.cart_remove, name="cart_remove"),
    path("cart/clear/", views.cart_clear, name="cart_clear"),
    path("cart/", views.cart, name="cart"),
    path("live/version/", views.live_version, name="live_version"),
    path("live/state/", views.live_state, name="live_state"),
    path("live/region/", views.live_region, name="live_region"),
    path("catalog/stock/", views.catalog_stock, name="catalog_stock"),
    path("items/", views.item_list, name="item_list"),
    path("items/new/", views.item_create, name="item_create"),
    path("items/<int:pk>/edit/", views.item_edit, name="item_edit"),
    path("items/<int:pk>/", views.item_detail, name="item_detail"),
    path("stock-takes/", views.stock_take_list, name="stock_take_list"),
    path("stock-takes/new/", views.stock_take_create, name="stock_take_create"),
    path("stock-takes/<int:pk>/", views.stock_take_detail, name="stock_take_detail"),
    path("stock-takes/print/", views.stock_take_print, name="stock_take_print"),
    path("onesignal/subscribe/", views.onesignal_subscribe, name="onesignal_subscribe"),
    path("onesignal/unsubscribe/", views.onesignal_unsubscribe, name="onesignal_unsubscribe"),
    path("onesignal/devices/", views.onesignal_devices, name="onesignal_devices"),
    path("OneSignalSDKWorker.js", views.onesignal_sw, name="onesignal_sw"),
]
