# Generated by Django 6.0.7 on 2026-07-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_conditionoption_statusoption_item_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
