# Generated by Django 6.0.7 on 2026-07-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('book_ahead', 'Book ahead'), ('check_out', 'Check Out'), ('check_in', 'Check In')], max_length=20),
        ),
    ]
