# Generated by Django 6.0.7 on 2026-07-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_category_item_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity_available',
        ),
        migrations.AddField(
            model_name='transaction',
            name='expected_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
