# Generated by Django 6.0.7 on 2026-07-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_maintenance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
