# Generated by Django 6.0.7 on 2026-07-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_item_quantity_maintenance_maintenance_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='taken_at',
            field=models.DateTimeField(blank=True, help_text='When the item is/was taken (book-ahead pickup).', null=True),
        ),
    ]
