# Generated by Django 6.0.7 on 2026-07-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_transaction_taken_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Live version',
            },
        ),
    ]
