# Generated by Django 6.0.7 on 2026-07-15 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_transaction_approval_status_transaction_decided_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_by_name',
            field=models.CharField(blank=True, help_text='Human-readable name of the admin who posted the update.', max_length=150),
        ),
        migrations.AddField(
            model_name='transaction',
            name='person_name',
            field=models.CharField(blank=True, help_text='Human-readable name of the member the transaction is for.', max_length=150),
        ),
        migrations.AddField(
            model_name='transaction',
            name='decided_by_name',
            field=models.CharField(blank=True, help_text='Human-readable name of the admin who decided the request.', max_length=150),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='reported_by_name',
            field=models.CharField(blank=True, help_text='Human-readable name of the person who reported the item.', max_length=150),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='completed_by_name',
            field=models.CharField(blank=True, help_text='Human-readable name of the person who returned the item.', max_length=150),
        ),
    ]
