# Generated by Django 6.0.7 on 2026-07-16 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_notification_email_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='voided',
            field=models.CharField(choices=[('none', 'Not voided'), ('voided', 'Voided')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided_by_name',
            field=models.CharField(blank=True, help_text='Human-readable name of the admin who voided the transaction.', max_length=150),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided_reason',
            field=models.TextField(blank=True, help_text='Why the transaction was voided.'),
        ),
    ]
