# Generated by Django 6.0.7 on 2026-07-16 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_transaction_voided_transaction_voided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='location',
            field=models.ForeignKey(blank=True, help_text="Where the item is while out for service (defaults to the item's location).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='inventory.location'),
        ),
    ]
