# Generated by Django 6.0.7 on 2026-07-18 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_requests(apps, schema_editor):
    """Turn every legacy single-item Transaction into a Request + RequestItem so
    the new multi-item model covers all history."""
    Transaction = apps.get_model("inventory", "Transaction")
    Request = apps.get_model("inventory", "Request")
    RequestItem = apps.get_model("inventory", "RequestItem")
    for txn in Transaction.objects.filter(request__isnull=True):
        request = Request.objects.create(
            user_id=txn.user_id,
            person_name=txn.person_name,
            transaction_type=txn.transaction_type,
            notes=txn.notes,
            created_at=txn.created_at,
            expected_return=txn.expected_return,
            taken_at=txn.taken_at,
            approval_status=txn.approval_status,
            voided=txn.voided,
            voided_by_id=txn.voided_by_id,
            voided_by_name=txn.voided_by_name,
            voided_at=txn.voided_at,
            voided_reason=txn.voided_reason,
            decided_by_id=txn.decided_by_id,
            decided_by_name=txn.decided_by_name,
            decided_at=txn.decided_at,
        )
        RequestItem.objects.create(
            request=request,
            item_id=txn.item_id,
            quantity=txn.quantity,
            location_id=txn.location_id,
            condition_id=txn.condition_id,
            transaction=txn,
        )
        txn.request = request
        txn.save(update_fields=["request"])


def reverse_backfill_requests(apps, schema_editor):
    Request = apps.get_model("inventory", "Request")
    Request.objects.all().delete()




class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_backfill_user_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, help_text='Human-readable name of the member the request is for.', max_length=150)),
                ('transaction_type', models.CharField(choices=[('book_ahead', 'Book ahead'), ('check_out', 'Check Out'), ('check_in', 'Check In')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return', models.DateTimeField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(blank=True, help_text='When the item is/was taken (book-ahead pickup).', null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('voided', models.CharField(choices=[('none', 'Not voided'), ('voided', 'Voided')], default='none', max_length=20)),
                ('voided_by_name', models.CharField(blank=True, help_text='Human-readable name of the admin who voided the request.', max_length=150)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('voided_reason', models.TextField(blank=True, help_text='Why the request was voided.')),
                ('decided_by_name', models.CharField(blank=True, help_text='Human-readable name of the admin who decided the request.', max_length=150)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.request'),
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_items', to='inventory.conditionoption')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='inventory.item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='inventory.location')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.request')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_item', to='inventory.transaction')),
            ],
        ),
        migrations.RunPython(backfill_requests, reverse_backfill_requests),
    ]
