# Generated by Django 6.0.7 on 2026-07-18 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_request_transaction_request_requestitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('staff', 'Staff'), ('teacher', 'Teacher'), ('student', 'Student'), ('guest', 'Guest')], max_length=20, unique=True)),
                ('label', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='LocationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='inventory.location')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_links', to='inventory.role')),
            ],
            options={
                'ordering': ['location__name', 'role__slug'],
                'unique_together': {('location', 'role')},
            },
        ),
        migrations.AddField(
            model_name='location',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles that may see this location. Left empty, a location is visible to everyone.', related_name='locations', through='inventory.LocationRole', through_fields=('location', 'role'), to='inventory.role'),
        ),
    ]
