# Generated by Django 6.0.7 on 2026-07-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_request_handed_over'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pinned updates stay at the top of the list and home panel.'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='style',
            field=models.CharField(choices=[('info', 'Info'), ('event', 'Event'), ('warning', 'Warning'), ('success', 'Good news')], default='info', help_text='Changes the accent colour and icon shown with the update.', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
