# Generated by Django 6.0.7 on 2026-07-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_alter_announcement_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='style',
            field=models.CharField(choices=[('info', 'Info'), ('event', 'Event'), ('alert', 'Alert'), ('warning', 'Warning'), ('maintenance', 'Maintenance'), ('closed', 'Closed'), ('success', 'Good news'), ('reminder', 'Reminder')], default='info', help_text='Changes the accent colour and icon shown with the update.', max_length=20),
        ),
    ]
