# Generated by Django 6.0.7 on 2026-07-19 00:48

from django.db import migrations, models


def backfill_reference_codes(apps, schema_editor):
    Request = apps.get_model("inventory", "Request")
    prefix = "KW-"
    highest = 0
    for code in Request.objects.values_list("reference_code", flat=True):
        if code and code.startswith(prefix):
            digits = code[len(prefix):]
            if digits.isdigit():
                highest = max(highest, int(digits))
    counter = highest
    for req in Request.objects.order_by("created_at").iterator():
        if not req.reference_code:
            counter += 1
            req.reference_code = f"{prefix}{counter:04d}"
            req.save(update_fields=["reference_code"])


def reverse_backfill(apps, schema_editor):
    Request = apps.get_model("inventory", "Request")
    Request.objects.update(reference_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_transaction_source_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reference_code',
            field=models.CharField(blank=True, help_text='Short desk-facing code (e.g. KW-0042) printed on the slip so staff can link returns precisely.', max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(backfill_reference_codes, reverse_backfill),
    ]
