# Generated by Django 6.0.7 on 2026-08-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_add_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('reservation', 'Reservation'), ('request', 'Request'), ('general', 'General'), ('reminder', 'Reminder')], default='general', max_length=20),
        ),
    ]
