# Generated by Django 6.0.7 on 2026-09-25 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_onesignal_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_total', models.PositiveIntegerField(default=0)),
                ('quantity_out', models.PositiveIntegerField(default=0)),
                ('quantity_maintenance', models.PositiveIntegerField(default=0)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_code', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['catalog_item__name', 'location__name'],
            },
        ),
        migrations.RenameIndex(
            model_name='onesignalplayer',
            new_name='inventory_o_user_id_3da695_idx',
            old_name='inventory_o_user_id_f9f1f9_idx',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('overdue', 'Overdue'), ('due_soon', 'Due soon'), ('upcoming_pickup_24h', 'Upcoming pickup 24h'), ('upcoming_pickup_1h', 'Upcoming pickup 1h'), ('upcoming_pickup_15min', 'Upcoming pickup 15min'), ('upcoming_pickup_admin_15min', 'Upcoming pickup admin 15min')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('sku',), name='unique_nonblank_catalog_item_sku'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='catalog_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='inventory.catalogitem'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='inventory.conditionoption'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='inventory.statusoption'),
        ),
        migrations.AlterUniqueTogether(
            name='stockentry',
            unique_together={('catalog_item', 'location')},
        ),
    ]
