# Generated by Django 6.0.7 on 2026-09-25 13:50

from django.db import migrations, models
import django.db.models.deletion


def backfill_catalog_and_stock(apps, schema_editor):
    Item = apps.get_model("inventory", "Item")
    CatalogItem = apps.get_model("inventory", "CatalogItem")
    StockEntry = apps.get_model("inventory", "StockEntry")

    for item in Item.objects.all():
        catalog = CatalogItem.objects.create(
            pk=item.pk,
            name=item.name,
            description=item.description,
            category=item.category,
            subcategory=item.subcategory,
            sku=item.sku,
            image=item.image,
            is_active=item.is_active,
            created_at=item.created_at,
        )
        StockEntry.objects.create(
            pk=item.pk,
            catalog_item=catalog,
            location_id=item.location_id,
            quantity_total=item.quantity_total,
            quantity_out=item.quantity_out,
            quantity_maintenance=item.quantity_maintenance,
            condition_id=item.condition_id,
            status_id=item.status_id,
            qr_image=item.qr_image,
            qr_code=item.qr_code,
            is_active=item.is_active,
            created_at=item.created_at,
        )


def update_stock_entry_sequence(apps, schema_editor):
    """Ensure the auto-increment sequence on StockEntry is past the max PK
    we explicitly set during backfill, so future inserts don't clash."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE sqlite_sequence SET seq = (SELECT IFNULL(MAX(id), 0) FROM inventory_stockentry) "
            "WHERE name = 'inventory_stockentry'"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0042_add_catalog_and_stock_models"),
    ]

    operations = [
        migrations.RunPython(backfill_catalog_and_stock, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(update_stock_entry_sequence, reverse_code=migrations.RunPython.noop),
    ]
