# Generated by Django 6.0.7 on 2026-09-25 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_backfill_catalog_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktakeitem',
            options={'ordering': ['item__catalog_item__name']},
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='inventory.stockentry'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='inventory.stockentry'),
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_items', to='inventory.stockentry'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.stockentry'),
        ),
    ]
