# Generated by Django 6.0.7 on 2026-09-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_alter_item_fks_to_stockentry'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_nonblank_item_sku',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
