# Generated by Django 6.0.7 on 2026-10-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_kit_kititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_location',
            field=models.ForeignKey(blank=True, help_text='The room/location assigned to this teacher.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teachers', to='inventory.location'),
        ),
    ]
